export type Verse = {
  id: string;
  topic: string;
  reference: string;
  text: string;
  meditationPrompt: string;
  source: string;
};

export const VERSES: Verse[] = [
  {
    id: 'verse-001',
    topic: '자녀들을 위한 말씀',
    reference: '시편 127:3',
    text: '자식은 여호와의 주신 기업이요 태의 열매는 그의 상급이로다',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-002',
    topic: '자녀들을 위한 말씀',
    reference: '시편 127:4',
    text: '젊은 자의 자식은 장사의 수중의 화살 같으니',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-003',
    topic: '자녀들을 위한 말씀',
    reference: '시편 127:5',
    text: '이것이 그 전통에 가득한 자는 복되도다 저희가 성문에서 그 원수와 말할 때에 수치를 당치 아니하리로다',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-004',
    topic: '자녀들을 위한 말씀',
    reference: '시편 128:1',
    text: '여호와를 경외하며 그 도에 행하는 자마다 복이 있도다',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-005',
    topic: '자녀들을 위한 말씀',
    reference: '시편 128:2',
    text: '네가 네 손이 수고한대로 먹을 것이라 네가 복되고 형통하리로다',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-006',
    topic: '자녀들을 위한 말씀',
    reference: '시편 128:3',
    text: '네 집 내실에 있는 네 아내는 결실한 포도나무 같으며 네 상에 둘린 자식은 어린 감람나무 같으리로다',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-007',
    topic: '자녀들을 위한 말씀',
    reference: '시편 128:4',
    text: '여호와를 경외하는 자는 이같이 복을 얻으리로다',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-008',
    topic: '자녀들을 위한 말씀',
    reference: '시편 128:5',
    text: '여호와께서 시온에서 네게 복을 주실찌어다 너는 평생에 예루살렘의 복을 보며',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-009',
    topic: '자녀들을 위한 말씀',
    reference: '시편 128:6',
    text: '네 자식의 자식을 볼찌어다 이스라엘에게 평강이 있을찌로다',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-010',
    topic: '자녀들을 위한 말씀',
    reference: '신명기 6:4',
    text: '이스라엘아 들으라 우리 하나님 여호와는 오직 하나인 여호와시니',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-011',
    topic: '자녀들을 위한 말씀',
    reference: '신명기 6:5',
    text: '너는 마음을 다하고 성품을 다하고 힘을 다하여 네 하나님 여호와를 사랑하라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-012',
    topic: '자녀들을 위한 말씀',
    reference: '신명기 6:6',
    text: '오늘날 내가 네게 명하는 이 말씀을 너는 마음에 새기고',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-013',
    topic: '자녀들을 위한 말씀',
    reference: '신명기 6:7',
    text: '네 자녀에게 부지런히 가르치며 집에 앉았을 때에든지 길에 행할 때에든지 누웠을 때에든지 일어날 때에든지 이 말씀을 강론할 것이며',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-014',
    topic: '자녀들을 위한 말씀',
    reference: '신명기 6:8',
    text: '너는 또 그것을 네 손목에 매어 기호를 삼으며 네 미간에 붙여 표를 삼고',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-015',
    topic: '자녀들을 위한 말씀',
    reference: '신명기 6:9',
    text: '또 네 집 문설주와 바깥 문에 기록할찌니라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-016',
    topic: '자녀들을 위한 말씀',
    reference: '신명기 6:20',
    text: '후일에 네 아들이 네게 묻기를 우리 하나님 여호와의 명하신 증거와 말씀과 규례와 법도가 무슨 뜻이뇨 하거든',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-017',
    topic: '자녀들을 위한 말씀',
    reference: '신명기 6:21',
    text: '너는 네 아들에게 이르기를 우리가 옛적에 애굽에서 바로의 종이 되었더니 여호와께서 권능의 손으로 우리를 애굽에서 인도하여 내셨나니',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-018',
    topic: '자녀들을 위한 말씀',
    reference: '신명기 6:24',
    text: '여호와께서 우리에게 이 모든 규례를 지키라 명하셨으니 이는 우리로 우리 하나님 여호와를 경외하여 항상 복을 누리게 하기 위하심이며 또 여호와께서 우리로 오늘날과 같이 생활하게 하려 하심이라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-019',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 1:7',
    text: '여호와를 경외하는 것이 지식의 근본이어늘 미련한 자는 지혜와 훈계를 멸시하느니라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-020',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 1:8',
    text: '내 아들아 네 아비의 훈계를 들으며 네 어미의 법을 떠나지 말라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-021',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 1:9',
    text: '이는 네 머리의 아름다운 관이요 네 목의 금사슬이니라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-022',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 1:10',
    text: '내 아들아 악한 자가 너를 꾈찌라도 좇지 말라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-023',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 1:15',
    text: '내 아들아 그들과 함께 길에 다니지 말라 네 발을 금하여 그 길을 밟지 말라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-024',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 1:23',
    text: '나의 책망을 듣고 돌이키라 보라 내가 나의 신을 너희에게 부어주며 나의 말을 너희에게 보이리라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-025',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 3:5',
    text: '너는 마음을 다하여 여호와를 의뢰하고 네 명철을 의지하지 말라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-026',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 3:6',
    text: '너는 범사에 그를 인정하라 그리하면 네 길을 지도하시리라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-027',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 3:11',
    text: '내 아들아 여호와의 징계를 경히 여기지 말라 그 꾸지람을 싫어하지 말라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-028',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 3:12',
    text: '대저 여호와께서 그 사랑하시는 자를 징계하시기를 마치 아비가 그 기뻐하는 아들을 징계함 같이 하시느니라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-029',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 4:1',
    text: '아들들아 아비의 훈계를 들으며 명철을 얻기에 주의하라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-030',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 4:6',
    text: '지혜를 버리지 말라 그가 너를 보호하리라 그를 사랑하라 그가 너를 지키리라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-031',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 4:7',
    text: '지혜가 제일이니 지혜를 얻으라 무릇 너의 얻은 것을 가져 명철을 얻을찌니라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-032',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 4:8',
    text: '그를 높이라 그리하면 그가 너를 높이 들리라 만일 그를 품으면 그가 너를 영화롭게 하리라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-033',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 4:20',
    text: '내 아들아 내 말에 주의하며 나의 이르는 것에 네 귀를 기울이라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-034',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 4:21',
    text: '그것을 네 눈에서 떠나게 말며 네 마음 속에 지키라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-035',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 4:22',
    text: '그것은 얻는 자에게 생명이 되며 그 온 육체의 건강이 됨이니라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-036',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 4:23',
    text: '무릇 지킬만한 것보다 더욱 네 마음을 지키라 생명의 근원이 이에서 남이니라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-037',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 4:24',
    text: '궤휼한 입을 네게서 버리며 사곡한 입술을 네게서 멀리 하라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-038',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 4:25',
    text: '네 눈은 바로 보며 네 눈꺼풀은 네 앞을 곧게 살펴',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-039',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 4:26',
    text: '네 발의 행할 첩경을 평탄케 하며 네 모든 길을 든든히 하라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-040',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 4:27',
    text: '좌로나 우로나 치우치지 말고 네 발을 악에서 떠나게 하라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-041',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 22:1',
    text: '많은 재물보다 명예를 택할 것이요 은이나 금보다 은총을 더욱 택할 것이니라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-042',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 22:4',
    text: '겸손과 여호와를 경외함의 보응은 재물과 영광과 생명이니라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-043',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 22:6',
    text: '마땅히 행할 길을 아이에게 가르치라 그리하면 늙어도 그것을 떠나지 아니하리라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-044',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 22:15',
    text: '아이의 마음에는 미련한 것이 얽혔으나 징계하는 채찍이 이를 멀리 쫓아내리라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-045',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 22:17',
    text: '너는 귀를 기울여 지혜 있는 자의 말씀을 들으며 내 지식에 마음을 둘찌어다',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-046',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 22:18',
    text: '이것을 네 속에 보존하며 네 입술에 있게 함이 아름다우니라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-047',
    topic: '자녀들을 위한 말씀',
    reference: '잠언 22:19',
    text: '내가 너로 여호와를 의뢰하게 하려 하여 이것을 오늘 특별히 네게 알게 하였노니',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-048',
    topic: '자녀들을 위한 말씀',
    reference: '에베소서 6:1',
    text: '자녀들아 너희 부모를 주 안에서 순종하라 이것이 옳으니라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-049',
    topic: '자녀들을 위한 말씀',
    reference: '에베소서 6:2',
    text: '네 아버지와 어머니를 공경하라 이것이 약속 있는 첫계명이니',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-050',
    topic: '자녀들을 위한 말씀',
    reference: '에베소서 6:4',
    text: '또 아비들아 너희 자녀를 노엽게 하지 말고 오직 주의 교양과 훈계로 양육하라',
    meditationPrompt: '이 말씀을 붙들고 자녀와 가정을 위해 오늘 무엇을 기도할까요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-051',
    topic: '감사에 관한 말씀',
    reference: '시편 100:1',
    text: '온 땅이여 여호와께 즐거이 부를찌어다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-052',
    topic: '감사에 관한 말씀',
    reference: '시편 100:2',
    text: '기쁨으로 여호와를 섬기며 노래하면서 그 앞에 나아갈찌어다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-053',
    topic: '감사에 관한 말씀',
    reference: '시편 100:3',
    text: '여호와가 우리 하나님이신줄 너희는 알찌어다 그는 우리를 지으신 자시요 우리는 그의 것이니 그의 백성이요 그의 기르시는 양이로다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-054',
    topic: '감사에 관한 말씀',
    reference: '시편 100:4',
    text: '감사함으로 그 문에 들어가며 찬송함으로 그 궁정에 들어가서 그에게 감사하며 그 이름을 송축할찌어다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-055',
    topic: '감사에 관한 말씀',
    reference: '시편 100:5',
    text: '대저 여호와는 선하시니 그 인자하심이 영원하고 그 성실하심이 대대에 미치리로다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-056',
    topic: '감사에 관한 말씀',
    reference: '시편 107:1',
    text: '여호와께 감사하라 그는 선하시며 그 인자하심이 영원함이로다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-057',
    topic: '감사에 관한 말씀',
    reference: '시편 107:2',
    text: '여호와께 구속함을 받은 자는 이같이 말할찌어다 여호와께서 대적의 손에서 저희를 구속하사',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-058',
    topic: '감사에 관한 말씀',
    reference: '시편 107:6',
    text: '이에 저희가 그 근심 중에 여호와께 부르짖으매 그 고통에서 건지시고',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-059',
    topic: '감사에 관한 말씀',
    reference: '시편 107:7',
    text: '또 바른 길로 인도하사 거할 성에 이르게 하셨도다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-060',
    topic: '감사에 관한 말씀',
    reference: '시편 107:8',
    text: '여호와의 인자하심과 인생에게 행하신 기이한 일을 인하여 그를 찬송할찌로다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-061',
    topic: '감사에 관한 말씀',
    reference: '시편 107:9',
    text: '저가 사모하는 영혼을 만족케 하시며 주린 영혼에게 좋은 것으로 채워주심이로다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-062',
    topic: '감사에 관한 말씀',
    reference: '시편 107:21',
    text: '여호와의 인자하심과 인생에게 행하신 기이한 일을 인하여 그를 찬송할찌로다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-063',
    topic: '감사에 관한 말씀',
    reference: '시편 107:22',
    text: '감사제를 드리며 노래하여 그 행사를 선포할찌로다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-064',
    topic: '감사에 관한 말씀',
    reference: '시편 118:1',
    text: '여호와께 감사하라 저는 선하시며 그 인자하심이 영원함이로다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-065',
    topic: '감사에 관한 말씀',
    reference: '시편 118:5',
    text: '내가 고통 중에 여호와께 부르짖었더니 여호와께서 응답하시고 나를 광활한 곳에 세우셨도다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-066',
    topic: '감사에 관한 말씀',
    reference: '시편 118:6',
    text: '여호와는 내 편이시라 내게 두려움이 없나니 사람이 내게 어찌할꼬',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-067',
    topic: '감사에 관한 말씀',
    reference: '시편 118:14',
    text: '여호와는 나의 능력과 찬송이시요 또 나의 구원이 되셨도다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-068',
    topic: '감사에 관한 말씀',
    reference: '시편 118:19',
    text: '내게 의의 문을 열찌어다 내가 들어가서 여호와께 감사하리로다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-069',
    topic: '감사에 관한 말씀',
    reference: '시편 118:21',
    text: '주께서 내게 응답하시고 나의 구원이 되셨으니 내가 주께 감사하리이다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-070',
    topic: '감사에 관한 말씀',
    reference: '시편 118:24',
    text: '이 날은 여호와의 정하신 것이라 이 날에 우리가 즐거워하고 기뻐하리로다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-071',
    topic: '감사에 관한 말씀',
    reference: '시편 118:28',
    text: '주는 나의 하나님이시라 내가 주께 감사하리이다 주는 나의 하나님이시라 내가 주를 높이리이다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-072',
    topic: '감사에 관한 말씀',
    reference: '시편 118:29',
    text: '여호와께 감사하라 그는 선하시며 그 인자하심이 영원함이로다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-073',
    topic: '감사에 관한 말씀',
    reference: '시편 136:1',
    text: '여호와께 감사하라 그는 선하시며 그 인자하심이 영원함이로다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-074',
    topic: '감사에 관한 말씀',
    reference: '시편 136:2',
    text: '모든 신에 뛰어나신 하나님께 감사하라 그 인자하심이 영원함이로다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-075',
    topic: '감사에 관한 말씀',
    reference: '시편 136:3',
    text: '모든 주에 뛰어나신 주께 감사하라 그 인자하심이 영원함이로다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-076',
    topic: '감사에 관한 말씀',
    reference: '시편 136:4',
    text: '홀로 큰 기사를 행하시는 이에게 감사하라 그 인자하심이 영원함이로다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-077',
    topic: '감사에 관한 말씀',
    reference: '시편 136:5',
    text: '지혜로 하늘을 지으신 이에게 감사하라 그 인자하심이 영원함이로다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-078',
    topic: '감사에 관한 말씀',
    reference: '시편 136:23',
    text: '우리를 비천한 데서 기념하신 이에게 감사하라 그 인자하심이 영원함이로다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-079',
    topic: '감사에 관한 말씀',
    reference: '시편 136:24',
    text: '우리를 우리 대적에게서 건지신 이에게 감사하라 그 인자하심이 영원함이로다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-080',
    topic: '감사에 관한 말씀',
    reference: '시편 136:25',
    text: '모든 육체에게 식물을 주신 이에게 감사하라 그 인자하심이 영원함이로다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-081',
    topic: '감사에 관한 말씀',
    reference: '시편 136:26',
    text: '하늘의 하나님께 감사하라 그 인자하심이 영원함이로다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-082',
    topic: '감사에 관한 말씀',
    reference: '골로새서 4:2',
    text: '기도를 항상 힘쓰고 기도에 감사함으로 깨어 있으라',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-083',
    topic: '감사에 관한 말씀',
    reference: '빌립보서 4:6',
    text: '아무 것도 염려하지 말고 오직 모든 일에 기도와 간구로 너희 구할 것을 감사함으로 하나님께 아뢰라',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-084',
    topic: '감사에 관한 말씀',
    reference: '데살로니가전서 5:16',
    text: '항상 기뻐하라',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-085',
    topic: '감사에 관한 말씀',
    reference: '데살로니가전서 5:17',
    text: '쉬지 말고 기도하라',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-086',
    topic: '감사에 관한 말씀',
    reference: '데살로니가전서 5:18',
    text: '범사에 감사하라 이는 그리스도 예수 안에서 너희를 향하신 하나님의 뜻이니라',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-087',
    topic: '감사에 관한 말씀',
    reference: '에베소서 5:20',
    text: '범사에 우리 주 예수 그리스도의 이름으로 항상 아버지 하나님께 감사하며',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-088',
    topic: '감사에 관한 말씀',
    reference: '골로새서 3:15',
    text: '그리스도의 평강이 너희 마음을 주장하게 하라 평강을 위하여 너희가 한 몸으로 부르심을 입었나니 또한 너희는 감사하는 자가 되라',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-089',
    topic: '감사에 관한 말씀',
    reference: '골로새서 3:16',
    text: '그리스도의 말씀이 너희 속에 풍성이 거하여 모든 지혜로 피차 가르치며 권면하고 시와 찬미와 신령한 노래를 부르며 마음에 감사함으로 하나님을 찬양하고',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-090',
    topic: '감사에 관한 말씀',
    reference: '골로새서 3:17',
    text: '또 무엇을 하든지 말에나 일에나 다 주 예수의 이름으로 하고 그를 힘입어 하나님 아버지께 감사하라',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-091',
    topic: '감사에 관한 말씀',
    reference: '빌립보서 1:3',
    text: '내가 너희를 생각할 때마다 나의 하나님께 감사하며',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-092',
    topic: '감사에 관한 말씀',
    reference: '빌립보서 1:4',
    text: '간구할 때마다 너희 무리를 위하여 기쁨으로 항상 간구함은',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-093',
    topic: '감사에 관한 말씀',
    reference: '시편 92:1',
    text: '지존자여 십현금과 비파와 수금의 정숙한 소리로 여호와께 감사하며 주의 이름을 찬양함이 좋으니이다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-094',
    topic: '감사에 관한 말씀',
    reference: '시편 95:2',
    text: '우리가 감사함으로 그 앞에 나아가며 시로 그를 향하여 즐거이 부르자',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-095',
    topic: '감사에 관한 말씀',
    reference: '시편 103:2',
    text: '내 영혼아 여호와를 송축하며 그 모든 은택을 잊지 말찌어다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-096',
    topic: '감사에 관한 말씀',
    reference: '시편 106:1',
    text: '할렐루야 여호와께 감사하라 그는 선하시며 그 인자하심이 영원함이로다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-097',
    topic: '감사에 관한 말씀',
    reference: '로마서 7:25',
    text: '우리 주 예수 그리스도로 말미암아 하나님께 감사하리로다',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-098',
    topic: '감사에 관한 말씀',
    reference: '고린도후서 2:14',
    text: '항상 우리를 그리스도 안에서 이기게 하시고 우리로 말미암아 각처에서 그를 아는 냄새를 나타내시는 하나님께 감사하노라',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-099',
    topic: '감사에 관한 말씀',
    reference: '고린도후서 9:15',
    text: '그 지극히 큰 은사를 인하여 하나님께 감사하노라',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-100',
    topic: '감사에 관한 말씀',
    reference: '히브리서 12:28',
    text: '그러므로 우리가 진동치 못할 나라를 받았은즉 은혜를 받자 이로 말미암아 경건함과 두려움으로 하나님을 기쁘시게 섬길찌니',
    meditationPrompt: '이 말씀을 읽으며 오늘 하나님께 감사할 한 가지는 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-101',
    topic: '위로와 소망의 말씀',
    reference: '시편 23:1',
    text: '여호와는 나의 목자시니 내가 부족함이 없으리로다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-102',
    topic: '위로와 소망의 말씀',
    reference: '시편 23:2',
    text: '그가 나를 푸른 초장에 누이시며 쉴만한 물 가으로 인도하시는도다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-103',
    topic: '위로와 소망의 말씀',
    reference: '시편 23:3',
    text: '내 영혼을 소생시키시고 자기 이름을 위하여 의의 길로 인도하시는도다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-104',
    topic: '위로와 소망의 말씀',
    reference: '시편 23:4',
    text: '내가 사망의 음침한 골짜기로 다닐찌라도 해를 두려워하지 않을 것은 주께서 나와 함께 하심이라 주의 지팡이와 막대기가 나를 안위하시나이다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-105',
    topic: '위로와 소망의 말씀',
    reference: '시편 23:5',
    text: '주께서 내 원수의 목전에서 내게 상을 베푸시고 기름으로 내 머리에 바르셨으니 내 잔이 넘치나이다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-106',
    topic: '위로와 소망의 말씀',
    reference: '시편 23:6',
    text: '나의 평생에 선하심과 인자하심이 정녕 나를 따르리니 내가 여호와의 집에 영원히 거하리로다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-107',
    topic: '위로와 소망의 말씀',
    reference: '시편 34:4',
    text: '내가 여호와께 구하매 내게 응답하시고 내 모든 두려움에서 나를 건지셨도다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-108',
    topic: '위로와 소망의 말씀',
    reference: '시편 34:6',
    text: '이 곤고한 자가 부르짖으매 여호와께서 들으시고 그 모든 환난에서 구원하셨도다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-109',
    topic: '위로와 소망의 말씀',
    reference: '시편 34:8',
    text: '너희는 여호와의 선하심을 맛보아 알찌어다 그에게 피하는 자는 복이 있도다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-110',
    topic: '위로와 소망의 말씀',
    reference: '시편 34:17',
    text: '의인이 외치매 여호와께서 들으시고 저희의 모든 환난에서 건지셨도다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-111',
    topic: '위로와 소망의 말씀',
    reference: '시편 34:18',
    text: '여호와는 마음이 상한 자에게 가까이 하시고 중심에 통회하는 자를 구원하시는도다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-112',
    topic: '위로와 소망의 말씀',
    reference: '시편 34:19',
    text: '의인은 고난이 많으나 여호와께서 그 모든 고난에서 건지시는도다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-113',
    topic: '위로와 소망의 말씀',
    reference: '시편 46:1',
    text: '하나님은 우리의 피난처시요 힘이시니 환난 중에 만날 큰 도움이시라',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-114',
    topic: '위로와 소망의 말씀',
    reference: '시편 46:2',
    text: '그러므로 땅이 변하든지 산이 흔들려 바다 가운데 빠지든지',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-115',
    topic: '위로와 소망의 말씀',
    reference: '시편 46:3',
    text: '바닷물이 흉용하고 뛰놀든지 그것이 넘침으로 산이 요동할찌라도 우리는 두려워 아니하리로다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-116',
    topic: '위로와 소망의 말씀',
    reference: '시편 46:5',
    text: '하나님이 그 성중에 거하시매 성이 요동치 아니할 것이라 새벽에 하나님이 도우시리로다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-117',
    topic: '위로와 소망의 말씀',
    reference: '시편 46:10',
    text: '이르시기를 너희는 가만히 있어 내가 하나님 됨을 알찌어다 내가 열방과 세계 중에서 높임을 받으리라 하시도다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-118',
    topic: '위로와 소망의 말씀',
    reference: '시편 62:1',
    text: '나의 영혼이 잠잠히 하나님만 바람이여 나의 구원이 그에게서 나는도다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-119',
    topic: '위로와 소망의 말씀',
    reference: '시편 62:2',
    text: '오직 저만 나의 반석이시요 나의 구원이시요 나의 산성이시니 내가 크게 요동치 아니하리로다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-120',
    topic: '위로와 소망의 말씀',
    reference: '시편 62:5',
    text: '나의 영혼아 잠잠히 하나님만 바라라 대저 나의 소망이 저로 좇아 나는도다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-121',
    topic: '위로와 소망의 말씀',
    reference: '시편 62:7',
    text: '나의 구원과 영광이 하나님께 있음이여 내 힘의 반석과 피난처도 하나님께 있도다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-122',
    topic: '위로와 소망의 말씀',
    reference: '시편 62:8',
    text: '백성들아 시시로 저를 의지하고 그 앞에 마음을 토하라 하나님은 우리의 피난처시로다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-123',
    topic: '위로와 소망의 말씀',
    reference: '시편 121:1',
    text: '내가 산을 향하여 눈을 들리라 나의 도움이 어디서 올꼬',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-124',
    topic: '위로와 소망의 말씀',
    reference: '시편 121:2',
    text: '나의 도움이 천지를 지으신 여호와에게서로다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-125',
    topic: '위로와 소망의 말씀',
    reference: '시편 121:3',
    text: '여호와께서 너로 실족지 않게 하시며 너를 지키시는 자가 졸지 아니하시리로다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-126',
    topic: '위로와 소망의 말씀',
    reference: '시편 121:4',
    text: '이스라엘을 지키시는 자는 졸지도 아니하고 주무시지도 아니하시리로다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-127',
    topic: '위로와 소망의 말씀',
    reference: '시편 121:7',
    text: '여호와께서 너를 지켜 모든 환난을 면케 하시며 또 네 영혼을 지키시리로다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-128',
    topic: '위로와 소망의 말씀',
    reference: '시편 121:8',
    text: '여호와께서 너의 출입을 지금부터 영원까지 지키시리로다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-129',
    topic: '위로와 소망의 말씀',
    reference: '이사야 41:10',
    text: '두려워 말라 내가 너와 함께 함이니라 놀라지 말라 나는 네 하나님이 됨이니라 내가 너를 굳세게 하리라 참으로 너를 도와 주리라 참으로 나의 의로운 오른손으로 너를 붙들리라',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-130',
    topic: '위로와 소망의 말씀',
    reference: '이사야 41:13',
    text: '이는 나 여호와 너의 하나님이 네 오른손을 붙들고 네게 이르기를 두려워 말라 내가 너를 도우리라 할 것임이니라',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-131',
    topic: '위로와 소망의 말씀',
    reference: '이사야 43:1',
    text: '야곱아 너를 창조하신 여호와께서 이제 말씀하시느니라 이스라엘아 너를 조성하신 자가 이제 말씀하시느니라 너는 두려워 말라 내가 너를 구속하였고 내가 너를 지명하여 불렀나니 너는 내 것이라',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-132',
    topic: '위로와 소망의 말씀',
    reference: '이사야 43:2',
    text: '네가 물 가운데로 지날 때에 내가 함께할 것이라 강을 건널 때에 물이 너를 침몰치 못할 것이며 네가 불 가운데로 행할 때에 타지도 아니할 것이요 불꽃이 너를 사르지도 못하리니',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-133',
    topic: '위로와 소망의 말씀',
    reference: '예레미야애가 3:22',
    text: '여호와의 자비와 긍휼이 무궁하시므로 우리가 진멸되지 아니함이니이다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-134',
    topic: '위로와 소망의 말씀',
    reference: '예레미야애가 3:23',
    text: '이것이 아침마다 새로우니 주의 성실이 크도소이다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-135',
    topic: '위로와 소망의 말씀',
    reference: '예레미야애가 3:24',
    text: '내 심령에 이르기를 여호와는 나의 기업이시니 그러므로 내가 저를 바라리라 하도다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-136',
    topic: '위로와 소망의 말씀',
    reference: '예레미야애가 3:25',
    text: '기다리는 자에게나 구하는 영혼에게 여호와는 선하시도다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-137',
    topic: '위로와 소망의 말씀',
    reference: '예레미야애가 3:31',
    text: '이는 주께서 영원토록 버리지 않으실 것임이며',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-138',
    topic: '위로와 소망의 말씀',
    reference: '예레미야애가 3:32',
    text: '저가 비록 근심케 하시나 그 풍부한 자비대로 긍휼히 여기실 것임이라',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-139',
    topic: '위로와 소망의 말씀',
    reference: '예레미야애가 3:33',
    text: '주께서 인생으로 고생하며 근심하게 하심이 본심이 아니시로다',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-140',
    topic: '위로와 소망의 말씀',
    reference: '요한복음 14:1',
    text: '너희는 마음에 근심하지 말라 하나님을 믿으니 또 나를 믿으라',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-141',
    topic: '위로와 소망의 말씀',
    reference: '요한복음 14:18',
    text: '내가 너희를 고아와 같이 버려두지 아니하고 너희에게로 오리라',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-142',
    topic: '위로와 소망의 말씀',
    reference: '요한복음 14:27',
    text: '평안을 너희에게 끼치노니 곧 나의 평안을 너희에게 주노라 내가 너희에게 주는 것은 세상이 주는 것 같지 아니하니라 너희는 마음에 근심도 말고 두려워하지도 말라',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-143',
    topic: '위로와 소망의 말씀',
    reference: '요한복음 16:33',
    text: '이것을 너희에게 이름은 너희로 내 안에서 평안을 누리게 하려함이라 세상에서는 너희가 환난을 당하나 담대하라 내가 세상을 이기었노라',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-144',
    topic: '위로와 소망의 말씀',
    reference: '로마서 8:28',
    text: '우리가 알거니와 하나님을 사랑하는 자 곧 그 뜻대로 부르심을 입은 자들에게는 모든 것이 합력하여 선을 이루느니라',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-145',
    topic: '위로와 소망의 말씀',
    reference: '로마서 8:31',
    text: '그런즉 이 일에 대하여 우리가 무슨 말하리요 만일 하나님이 우리를 위하시면 누가 우리를 대적하리요',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-146',
    topic: '위로와 소망의 말씀',
    reference: '로마서 8:38',
    text: '내가 확신하노니 사망이나 생명이나 천사들이나 권세자들이나 현재 일이나 장래 일이나 능력이나',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-147',
    topic: '위로와 소망의 말씀',
    reference: '로마서 8:39',
    text: '높음이나 깊음이나 다른 아무 피조물이라도 우리를 우리 주 그리스도 예수 안에 있는 하나님의 사랑에서 끊을 수 없으리라',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-148',
    topic: '위로와 소망의 말씀',
    reference: '로마서 15:13',
    text: '소망의 하나님이 모든 기쁨과 평강을 믿음 안에서 너희에게 충만케 하사 성령의 능력으로 소망이 넘치게 하시기를 원하노라',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-149',
    topic: '위로와 소망의 말씀',
    reference: '베드로전서 5:7',
    text: '너희 염려를 다 주께 맡겨 버리라 이는 저가 너희를 권고하심이니라',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
  {
    id: 'verse-150',
    topic: '위로와 소망의 말씀',
    reference: '요한계시록 21:4',
    text: '모든 눈물을 그 눈에서 씻기시매 다시 사망이 없고 애통하는 것이나 곡하는 것이나 아픈 것이 다시 있지 아니하리니 처음 것들이 다 지나갔음이러라',
    meditationPrompt: '이 말씀을 붙들고 오늘 하나님께 맡겨야 할 마음의 짐은 무엇인가요?',
    source: '사용자 제공 말씀 목록',
  },
];

function getSeoulDateKey(date: Date = new Date()): string {
  const formatter = new Intl.DateTimeFormat('en-CA', {
    timeZone: 'Asia/Seoul',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  });
  const parts = formatter.formatToParts(date);
  const year = parts.find((part) => part.type === 'year')?.value ?? '1970';
  const month = parts.find((part) => part.type === 'month')?.value ?? '01';
  const day = parts.find((part) => part.type === 'day')?.value ?? '01';
  return `${year}-${month}-${day}`;
}

function hashString(value: string): number {
  let hash = 0;
  for (let index = 0; index < value.length; index += 1) {
    hash = (hash * 31 + value.charCodeAt(index)) >>> 0;
  }
  return hash;
}

export function getTodayVerse(date: Date = new Date()): Verse {
  const dateKey = getSeoulDateKey(date);
  const randomIndex = hashString(dateKey) % VERSES.length;
  return VERSES[randomIndex];
}

export function formatKoreanDate(date: Date): string {
  return new Intl.DateTimeFormat('ko-KR', {
    timeZone: 'Asia/Seoul',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    weekday: 'long',
  }).format(date);
}

export type FavoriteVerse = Verse & {
  savedAt: string;
};

export const FAVORITES_STORAGE_KEY = 'daily-bible-meditation:favorites';

export function readFavoriteVerses(): FavoriteVerse[] {
  if (typeof window === 'undefined') {
    return [];
  }

  const raw = window.localStorage.getItem(FAVORITES_STORAGE_KEY);
  if (!raw) {
    return [];
  }

  try {
    const parsed = JSON.parse(raw) as FavoriteVerse[];
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

export function writeFavoriteVerses(items: FavoriteVerse[]) {
  window.localStorage.setItem(FAVORITES_STORAGE_KEY, JSON.stringify(items));
}
